FROM python:latest

WORKDIR /usr/src/app

RUN pip install --no-cache-dir \
    django-mongodb-backend \
    djangorestframework \
    "pymongo[srv]" \
    python-dotenv \
    django-cors-headers

COPY . .

WORKDIR /usr/src/app/djangotutorial/termo_backend

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
