# Generated by Django 6.0.3 on 2026-03-14 01:43

import django.core.validators
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Must be exactly 5 characters.', max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
