# Generated by Django 6.0.4 on 2026-04-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_add_initial_words'),
        ('base', '0003_add_initial_words'),
    ]

    operations = [
    ]
